# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKXwj10BYnFq432m4TqlsSHezIVykmFD
"""

# Task 2A: First n Fibonacci numbers using recursive definition

def fib(n):
    if(n == 1):
      return 0

    elif(n == 2):
      return 1

    else:
      return ((fib(n-1)) + (fib(n-2)))

n = int(input("n: "))

file = open("fib_numbers.txt", "w")

for m in range(1,(n+1)):
  file.write(str(fib(m)) + "\n")
  print(fib(m))

file.close()





# Storing values in memory
# Task 2B
fib_list = []
def fib(n):

      if(n == 1):
        return 0

      elif(n == 2):
        return 1

      elif(len(fib_list)>=n):
        return fib_list[n-1]

      else:
        return ((fib(n-1)) + (fib(n-2)))

n = int(input("n: "))

file = open("fib_numbers.txt", "w")

for m in range(1,(n+1)):
    file.write(str(fib(m)) + "\n")
    num = fib(m)
    fib_list.append(num)
    print(fib(m))

file.close()